name: Infra

on:
  #Habilita el trigger workflow cuando sucede un Push o un Pull en el master del repo 
  push:
    branches:
      - master
    paths:
      - src/**
  pull_request_target: 
    branches: 
      - master
    paths:
      - src/**  
  # Enable the manual tab in GitHub
  workflow_dispatch:

    #tags:
    #- '*'

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRETE_ID }}
      AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
